apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
