apiVersion: v1
kind: Pod
metadata:
  name: validation-svc-pod
spec:
  containers:
    - name: validation-svc-container
      image: sustain/validation-service:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 50059
      command:
        - "python3 -m overlay --master --port=50059"
      env:
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP