apiVersion: v1
kind: Pod
metadata:
  name: validation-svc-worker
spec:
  nodeName: lattice-134
  containers:
    - name: validation-svc-worker
      image: sustain/validation-service:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 50058
      command: ["python3", "-m", "overlay", "--worker", "--master-uri=<validation-svc-master-ip>", "--port=50058"]
      env:
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
