apiVersion: v1
kind: Pod
metadata:
  name: validation-svc-flask
spec:
  nodeName: lattice-100
  containers:
    - name: validation-svc-flask
      image: sustain/validation-service:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 50057
      command: [ "python3", "-m", "overlay", "--flaskserver", "--master_uri=<validation-svc-master-ip>:<master-port>", "--port=50057" ]
      env:
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              filedPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP