apiVersion: v1
kind: Pod
metadata:
  name: validation-svc-master
spec:
  nodeName: lattice-100
  containers:
    - name: validation-svc-master
      image: sustain/validation-service:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 50059
      command: ["python3", "-m", "overlay", "--master", "--port=50059"]
      env:
        - name: DB_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DB_PORT
          value: 27018
        - name: DB_NAME
          value: sustaindb
        - name: MODELS_DIR
          value: /tmp/validation-service/saved_models
