apiVersion: v1
kind: Service
metadata:
  name: validation-service
spec:
  type: NodePort
  selector:
    name: validation-svc-master
  ports:
    - name: master-port
      port: 50059
      nodePort: 30036
      protocol: http
